// import AppReal from './1-REAL-REACT/AppReal';
// import AppRendering from './2-RENDERING-PROCESS/AppRendering';
// import AppInterview from './3-INTERVIEW/AppInterview';
// import AppMapFilter from './4-MAP-FILTER-REDUCE/AppMapFilter';
// import AppClass from './5-CLASS-FUNCITONAL/AppClass';
// import AppStateProp from './6-STAT-PROP/AppStateProp';
// import AppTypes from './7-TYPES-COMPONENTS/AppTypes';
// import FormulaFetch from './0-REACT-FORMULA/1-FETCH-DEMO/FormulaFetch';
// import FormulaRandom from './0-REACT-FORMULA/2-RANDOM-JOKE/FormulaRandom';
// import FormulaStock from './0-REACT-FORMULA/3-STOCKS/FormulaStock';
// import UseStateHook from './8-HOOKS/1-USE-STATE/UseStateHook';
// import UseEffectHook from './8-HOOKS/2-USE-EFFECT/UseEffectHook';
// import Counter from './8-HOOKS/3-USEFFECT-POLLYFILL/Counter';
// import UseRefHook from './8-HOOKS/4-USERREF/UseRefHook';
// import UseContextHook from './8-HOOKS/5-USECONTEXT/UseContextHook';
// import AppDarkLight from './8-HOOKS/6-DARK-LIGHT-EFFECT/AppDarkLight';
// import UseReducerHook from './8-HOOKS/7-USEREDUCER-HOOK/UseReducerHook';
import CounterWays from './8-HOOKS/8-USEMEMO-CALLBACL/CounterWays';
import NoOptimisation from './8-HOOKS/8-USEMEMO-CALLBACL/CounterWays';
import UseMemoCallback from './8-HOOKS/8-USEMEMO-CALLBACL/UseMemoCallback';
import CounterHooks from './9-CUSTOM-HOOKS/0-COUNTER/components/CounterHooks';
import UseWindowComp from './9-CUSTOM-HOOKS/1-USEWINDOWSIZE/components/UseWindowComp';
import PostCompFetch from './9-CUSTOM-HOOKS/2-USEFETCH/components/PostCompFetch';

function App() {
  // 0- 1-FETCH-DEMO return <FormulaFetch />;
  // 0-2-RANDOM-JOKE // return <FormulaRandom />;
  // 0- 3-STOCKS return <FormulaStock />;
  // 1-REAL-REACT return <AppReal />;
  // 2-RENDERING-PROCESS return <AppRendering />;
  // 3- INTERVIEW return <AppInterview />;
  // 4-map-filter-REDUCE return <AppMapFilter />;
  // 5-CLASS-FUNCTIONAL return <AppClass />;
  // 6-STATE-PROP return <AppStateProp />;
  // 7-TYPES-OF-COMPONENTS return <AppTypes />;
  // 8-HOOKS 1-USESTATE return <UseStateHook />;
  // 8-HOOKS 2-USEEFFECT return <UseEffectHook />;
  // 8-HOOKS 3-USEEFFECTPOLLYFILL return <Counter />;
  // 8-HOOKS 4-USEREFHOK return <UseRefHook />;
  // 8-HOOKS 5-USECONTEXT return <UseContextHook />;
  // 8-hooks 6-DARK-LIGHT-EFFECT return <AppDarkLight />;
  // 8-HOOKS 7-USEREDUCERHOOK return <UseReducerHook />;
  // 8-HOOKS 8-USEMEMOCALLBACK return <UseMemoCallback />;
  // 8-HOOKS 8-USEMEMOCALLBACK return <CounterWays />;
  // 9-CUSTOM-HOOKS 0-COUNTER return <CounterHooks />;
  // 9-CUSTOM-HOOKS 1-USEWINDOWSIZE return <UseWindowComp />;
  // 9-CUSTOM-HOOKS 1-USEWINDOWSIZE
  return <PostCompFetch />;
}
export default App;
